// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: dwarf.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dwarf_Create_FullMethodName = "/pb.Dwarf/Create"
)

// DwarfClient is the client API for Dwarf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DwarfClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type dwarfClient struct {
	cc grpc.ClientConnInterface
}

func NewDwarfClient(cc grpc.ClientConnInterface) DwarfClient {
	return &dwarfClient{cc}
}

func (c *dwarfClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Dwarf_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DwarfServer is the server API for Dwarf service.
// All implementations must embed UnimplementedDwarfServer
// for forward compatibility.
type DwarfServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedDwarfServer()
}

// UnimplementedDwarfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDwarfServer struct{}

func (UnimplementedDwarfServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDwarfServer) mustEmbedUnimplementedDwarfServer() {}
func (UnimplementedDwarfServer) testEmbeddedByValue()               {}

// UnsafeDwarfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DwarfServer will
// result in compilation errors.
type UnsafeDwarfServer interface {
	mustEmbedUnimplementedDwarfServer()
}

func RegisterDwarfServer(s grpc.ServiceRegistrar, srv DwarfServer) {
	// If the following call pancis, it indicates UnimplementedDwarfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dwarf_ServiceDesc, srv)
}

func _Dwarf_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DwarfServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dwarf_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DwarfServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dwarf_ServiceDesc is the grpc.ServiceDesc for Dwarf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dwarf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dwarf",
	HandlerType: (*DwarfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Dwarf_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dwarf.proto",
}
